version: '3.8'

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=mrs_adm1n
      - POSTGRES_PASSWORD=maman06!
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  next:
    depends_on:
      - postgres
    container_name: myrollersquad
    build:
      context: myrollersquad
      dockerfile: Dockerfile
    environment:
    - DATABASE_URL=postgresql://mrs_adm1n:maman06!@localhost:5432/myrollersquad?schema=public
    ports:
      - 3000:3000
    volumes:
      - ./myrollersquad:/app
      - /app/node_modules
      - /app/.next

volumes:
  db_data: {}
